### ISSUE TITLE
 Component ili9xxx.display took a long time for an operation (0.16 s).

### ISSUE THREAD

**Issue by leifnel** [BOlaerts/ESP32-2432s028#6]
[18:06:20][W][component:214]: Component ili9xxx.display took a long time for an operation (0.16 s).
[18:06:20][W][component:215]: Components should block for at most 20-30ms.

**Comment by BOlaerts** [comment]
Hi leifnel, according to https://github.com/esphome/issues/issues/4712 you could try to increase the I2C frequency to 400kHz as a workaround...
I cannot try this for the moment because I have other issues with my board.

**Comment by binagun** [comment]
Hi i just tried the code example but it seems to draw the image in the wrong orientation, leaving a band of noise on the right hand of the display ( assuming the usb-c port is left ). i assume that it might be an easy fix some where however im not wel versed with display drawing code and lcd libs

**Comment by BOlaerts** [comment]
https://esphome.io/changelog/2023.7.0.html
These 2 log lines may show up in the most recent version of ESPHome due to the log level being changed from verbose to warning.

You can hide the message, but it wont change the fact that the component is taking a long time.

`logger:
  logs:
    component: ERROR`

For some components this is actually expected like displays which have a lot of drawing and pixel/data moving.
For the majority of sensors, it means that they are doing too much processing or waiting for responses instead of letting ESPHome get on with business until the data is ready.
